site_name: The World of Sylvarus
theme:
  name: material
  features:
  - navigation.instant
  - navigation.top
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - content.action.edit
  - content.code.copy
extra_css:
- assets/custom.css
markdown_extensions:
- markdown_include.include
plugins:
- search
- include-markdown
- minify:
    minify_html: true
