site_name: The World of Sylvarus

theme:
  name: material
  palette:
    scheme: slate  # Dark mode scheme
    primary: 'orange'
    accent: 'amber'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate

extra_css:
  - assets/custom.css

markdown_extensions:
    - markdown_include.include

plugins:
  - search
  - include-markdown
  - minify:
      minify_html: true

theme:
  name: material
  features:
    - navigation.instant         # smooth transitions
    - navigation.top            # back-to-top button
    - navigation.tabs           # tabbed nav bar
    - navigation.sections       # collapsible sections
    - toc.integrate             # integrates TOC into mobile nav
    - content.action.edit       # optional "edit on GitHub"
    - content.code.copy         # adds copy buttons to code blocks
